title: Encuentro Colectiva
email: colectiva@ciudadaniai.org
description: ""
baseurl: //colectiva.ciudadaniai.org
github_username:  jekyll
analytics: ''
jquery_version: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
